[Wikings]
source            = imaps://jordan%40smileywikings.com@imap.migadu.com:993
outgoing          = smtps://jordan%40smileywikings.com@smtp.migadu.com:993

source-cred-cmd	  = pass accounts/email/jordan@smileywikings.com
outgoing-cred-cmd = pass accounts/email/jordan@smileywikings.com

default           = INBOX
from              = Jordan Walker <jordan@smileywikings.com>
cache-headers     = true

pgp-auto-sign     = true
pgp-key-id        = B099E1E94107C373E5CCB5596FE5F9930A004EB0

[Personal]
source            = imaps://jordan%40jordanwalker.us@imap.migadu.com:993
outgoing          = smtps://jordan%40jordanwalker.us@smtp.migadu.com:993

source-cred-cmd	  = pass jordanwalker.us/email/jordan
outgoing-cred-cmd = pass jordanwalker.us/email/jordan

default           = INBOX
from              = Jordan Walker <jordan@jordanwalker.us>
cache-headers     = true

[Unicron]
source            = imaps://consulting%40unicron.fi@imap.migadu.com:993
outgoing          = smtps://consulting%40unicron.fi@smtp.migadu.com:993

source-cred-cmd	  = pass accounts/email/consulting@unicron.fi
outgoing-cred-cmd = pass accounts/email/consulting@unicron.fi

default           = INBOX
from              = Jordan Walker <consulting@unicron.fi>
cache-headers     = true
